# Generated by Django 3.0.4 on 2020-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
